### ISSUE TITLE
大语言模型API配置指南

### ISSUE THREAD

**Issue by guxi0614** [mannaandpoem/OpenManus#296]
# 大语言模型API配置指南

本指南提供了如何配置和使用不同大语言模型API的详细说明，包括硅基流动的Qwen/QwQ-32B模型和Deepseek的Deepseek-v3模型。

### 硅基流动: Qwen/QwQ-32B模型

```toml
# 全局LLM配置
[llm]
# 模型名称
model = "Qwen/QwQ-32B"
# API基础URL
base_url = "https://api.siliconflow.cn/v1"
# 你的API密钥 (请替换为你自己的密钥)
api_key = "sk-你的API密钥"
# 最大生成标记数
max_tokens = 4096
# 温度参数 (0.0表示最确定性的输出)
temperature = 0.0
```

### Deepseek: Deepseek-v3模型

```toml
# 全局LLM配置
[llm]
# 模型名称
model = "deepseek-chat"
# API基础URL
base_url = "https://api.deepseek.com/v1"
# 你的API密钥 (请替换为你自己的密钥)
api_key = "sk-你的API密钥"
# 最大生成标记数
max_tokens = 4096
# 温度参数 (0.0表示最确定性的输出)
temperature = 0.0
```

### 浏览器安装

为了避免潜在问题和确保Web交互功能正常工作，建议安装Playwright浏览器：

```bash
playwright install
```

这将安装所有必要的浏览器依赖，确保项目能够正常进行网页抓取和自动化操作。

## 使用提示

1. **API密钥安全**: 请确保不要在公共场合分享你的API密钥。使用时替换`sk-你的API密钥`为你的实际密钥。

2. **参数调整**: 可以根据需要调整`max_tokens`和`temperature`参数。温度越低，输出越确定；温度越高，输出越多样。

3. **配置文件位置**: 将以上配置保存在项目的配置文件中（通常为`.toml`或`.yaml`格式）。

4. **依赖安装**: 除了Playwright浏览器外，确保已安装所有必要的Python依赖。

## 已知问题和限制

虽然上述配置可以成功运行，但存在一些需要注意的问题：

1. **效率问题**: 使用这些API可能会遇到响应速度慢的情况，特别是在处理复杂任务时。

2. **API超时**: 有时API调用可能会超时，尤其是在网络不稳定或服务负载高的情况下。

3. **文件保存不稳定**: 生成的文件可能不总是能成功下载或保存，这可能需要多次尝试或实现重试机制。

这些是目前已知的局限性，我们正在努力解决这些问题。如有更好的解决方案，欢迎社区贡献。

---

*注: 本指南提供的是基本配置和使用信息，仅供参考。实际应用中可能需要根据具体需求和环境做进一步调整。*
