### ISSUE TITLE
Requesting Gemini Model Access

### ISSUE THREAD

**Issue by vishaldwdi** [mannaandpoem/OpenManus#669]
Hi community,

Requesting cohesive Gemini Model access. I've tried changing model via config.toml and ran test yet it showed error command line showed error as code was trying to access OpenAI model. Therefore, I believe there is some error.

Gemini models supports vision natively and have great rate limits.

**Comment by hthuong09** [comment]
You can use Gemini's OpenAI-compatible endpoint.

```toml
[llm]
model = "gemini-2.0-flash"
base_url = "https://generativelanguage.googleapis.com/v1beta/openai/"
api_key = "xxx"
```
